### ISSUE TITLE
Doesn't seem to be doing anything expect deleting channels

### ISSUE THREAD

**Issue by No-Clever-Username** [Naim2000/system-channel-restorer#2]
I have a pal Wii if that means anything, anyways, I tried reistalling the Wii shop channel since it keeps bugging me for updates.

Five minutes later which consists of nothing happening since there's no progress bar or anything to indicate how's it's going. I had no choice but shutting off the Wii since it seems like it frozen. When I boot it up I noticed that the Wii shop channel is gone, I presume deleted to be replaced with the new channel, which never happened. This happened 3 times before I ragequit.

Yeah, I'm sticking to NUS downloader. Be better at coding, m8

**Comment by Ingunar** [comment]
You feel that you can code better? Do it. 
You don't have to patronise others.

You don't have to use the app. The DEV doesn't owe you anything. Bugs happen.

"Be better" is something YOU should consider doing after that comment.

**Comment by No-Clever-Username** [comment]
What a weird, antagonizing response to me just reporting a possible bug...

**Comment by Ingunar** [comment]
It is not weird, it is appropriate.
You can report the bug without being patronising.

Some people are new to coding or they are still learning.

Have some respect.

**Comment by No-Clever-Username** [comment]
Oh relax, your acting as if I kicked his dog or something. If you stop being this dramatic, you'll live a better life. Now stop wasting my time and go bark at someone else.

**Comment by Ingunar** [comment]
Not taking advices from rude, entitled brats.

**Comment by No-Clever-Username** [comment]
The only person who's acting rude is you m8.
